images:
  airflow:
    repository: cryptalytics/airflow
    tag: latest
    pullPolicy: Never

env:
  - name: "AIRFLOW_VAR_MONGO_URI"
    value: "mongodb://mongodb:27017/cryptalytics"
  - name: "AIRFLOW_VAR_IMAGE_PULL_POLICY"
    value: "Never"
  - name: "AIRFLOW_VAR_DELTA_CANDLES_PATH"
    value: "/data/delta/candles"
  - name: "AIRFLOW_CONN_INGESTION_GRPC"
    value: "grpc://ingestion:50051?extra__grpc__auth_type=NO_AUTH"

executor: KubernetesExecutor

data:
  metadataSecretName: ~
  metadataConnection:
    user: postgres
    pass: airflow
    protocol: postgresql
    host: airflow-postgresql.cryptalytics
    port: 5432
    db: airflow

apiServer:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 15
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 15
    failureThreshold: 10

scheduler:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
    timeoutSeconds: 60
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 10

dagProcessor:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"

triggerer:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 10

workers:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

postgresql:
  enabled: true
  auth:
    postgresPassword: airflow
    database: airflow

redis:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/LuoZihYuan/cryptalytics.git
    branch: main
    subPath: orchestration

config:
  core:
    load_examples: "False"
    dagbag_import_timeout: "120"
  kubernetes_executor:
    namespace: "cryptalytics"
    delete_worker_pods: "True"
    delete_worker_pods_on_failure: "False"

connections:
  - id: ingestion_grpc
    type: grpc
    host: ingestion
    port: 50051
    extra: '{"auth_type": "NO_AUTH"}'

serviceAccount:
  name: airflow-worker