apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - airflow-rbac.yaml
  - ingestion.yaml
  - tick-processor.yaml
  - fluent-bit.yaml
helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: "1.19.0"
    releaseName: airflow
    namespace: cryptalytics
    valuesFile: airflow-values.yaml
  - name: mongodb
    repo: https://charts.bitnami.com/bitnami
    version: "18.6.11"
    releaseName: mongodb
    namespace: cryptalytics
    valuesFile: mongodb-values.yaml
