# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fingestion.proto\x12\tingestion\"K\n\x10SubscribeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x17\n\ndag_run_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_dag_run_id\"5\n\x11SubscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x12UnsubscribeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"7\n\x13UnsubscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\x18ListSubscriptionsRequest\",\n\x19ListSubscriptionsResponse\x12\x0f\n\x07symbols\x18\x01 \x03(\t2\x88\x02\n\x10IngestionService\x12\x46\n\tSubscribe\x12\x1b.ingestion.SubscribeRequest\x1a\x1c.ingestion.SubscribeResponse\x12L\n\x0bUnsubscribe\x12\x1d.ingestion.UnsubscribeRequest\x1a\x1e.ingestion.UnsubscribeResponse\x12^\n\x11ListSubscriptions\x12#.ingestion.ListSubscriptionsRequest\x1a$.ingestion.ListSubscriptionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=30
  _globals['_SUBSCRIBEREQUEST']._serialized_end=105
  _globals['_SUBSCRIBERESPONSE']._serialized_start=107
  _globals['_SUBSCRIBERESPONSE']._serialized_end=160
  _globals['_UNSUBSCRIBEREQUEST']._serialized_start=162
  _globals['_UNSUBSCRIBEREQUEST']._serialized_end=199
  _globals['_UNSUBSCRIBERESPONSE']._serialized_start=201
  _globals['_UNSUBSCRIBERESPONSE']._serialized_end=256
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_start=258
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_end=284
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_start=286
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_end=330
  _globals['_INGESTIONSERVICE']._serialized_start=333
  _globals['_INGESTIONSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
