apiVersion: v1
kind: PersistentVolume
metadata:
  name: delta-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/delta
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delta-data
  namespace: cryptalytics
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
